######################################################################
#
# File name : mips_test_compile.do
# Created on: Sat Dec 14 12:01:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\ModelSim\\win64\\vlib modelsim_lib/work
E:\\ModelSim\\win64\\vlib modelsim_lib/msim

E:\\ModelSim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\ModelSim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\ModelSim\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../lab8.srcs/sources_1/new/ALU.v" \
"../../../../lab8.srcs/sources_1/new/ALU_DEC.v" \
"../../../../lab8.srcs/sources_1/new/COMP.v" \
"../../../../lab8.srcs/sources_1/new/DEC.v" \
"../../../../lab8.srcs/sources_1/new/DM.v" \
"../../../../lab8.srcs/sources_1/new/IM.v" \
"../../../../lab8.srcs/sources_1/new/MUX2.v" \
"../../../../lab8.srcs/sources_1/new/PC.v" \
"../../../../lab8.srcs/sources_1/new/RF.v" \
"../../../../lab8.srcs/sources_1/new/RM_DEC.v" \
"../../../../lab8.srcs/sources_1/new/mips.v" \
"../../../../lab8.srcs/sources_1/new/signextend.v" \
"../../../../lab8.srcs/sim_1/new/mips_test.v" \


# compile glbl module
E:\\ModelSim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

