######################################################################
#
# File name : mips_test_wave.do
# Created on: Fri Dec 13 23:51:50 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
