######################################################################
#
# File name : mips_test_simulate.do
# Created on: Sat Dec 14 12:01:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.mips_test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {mips_test_wave.do}

view wave
view structure
view signals

do {mips_test.udo}

run 1000ns
